### ISSUE TITLE
컨트롤러 및 서비스 구현 (8)

### ISSUE THREAD

**Issue by jm9293** [jm9293/gettingstarted-kotlin-spring-vue#2]
JSON DIFF 구현 및 캐싱 구현
JSON 비교전 정렬
depth에 제한이 없도록 재귀구현

**Comment by kimwz** [comment]
2번 요구사항을 좀더 명확히 해드리면, JSON 비교하기를 누른뒤 결과페이지에서 해당 주소를 친구에게 공유해서 접속해도 동일한 페이지가 뜨는 것을 의미합니다.

**Comment by kimwz** [comment]
이미 구현하셨다면 계속 진행하셔도 무관하지만, JSON은 Javascript Object 를 표현하기 위한 구조라서 Javascript에서 비교하시면 훨씬 쉽습니다.

**Comment by jm9293** [comment]
감사합니다. 라우터 이용해서 url 공유시 같은 결과가 나오도록 구현해보겠습니다. 비교는 이미 서버에서 하도록 구현해놨습니다.



2021년 2월 19일 (금) 오전 10:49, Karl Woojung Kim <notifications@github.com>님이 작성:

**Comment by kimwz** [comment]
1. 코틀린 문법 공부
자바와 유사한 점이 많으나 부족한게 많은것 같습니다. 일단 IDE에 도움을 받으며 해봤습니다. 문법적으로 간결하지 못한것이 있을수 있는데 너그럽게 봐주시면 감사하겠습니다.

생각보다 잘하시고 계신것 같습니다.

2. GET , POST 에 쿼리값 KEY의 생성방식
아무리 생각해도 각JSON 비교에 대한 고유한 값을 만들 방법이 마땅히 생각이 안나 해시코드를 만든뒤 16진수로 줄여서 사용했는데 더 좋은 방법을 생각하고 계셨으면 알려주시면 감사하겠습니다.
(JSON이 너무 길어지면 key 값이 길어지기 때문입니다.) 

SHA 해시코드를 사용하셔도 됩니다. JSON이 길어져도 키값의 길이는 늘어나지 않습니다.

3. 결과값에 대한 캐싱을 DB에서 하는게 성능적으로 맞는지
사실 처음에 서버에다 맵을 만들어서 담을까라는 생각도 해봤는데 서버가 꺼지면 없어지기도 하고 JPA도 한번 사용하게 맞는거 같아서 DB에 값을 담았습니다. 이부분도 실무에서 어떻게 하실것인지 궁금합니다.

실제 서비스를 만들었다면, JSON1, JSON2 를 서버에 저장해두고 client side 에서 비교해서 결과값을 생성해서 출력하는것이 좋습니다.
(사용자 성능 이용을 통해 서버 데이터 절약, 서버 부하 감소)
이미 서버에서 비교하는 연산을 만들었으니 이를 매번 이용하셔도 될듯합니다.
서버가 떠있는 동안이라도 서버내 메모리를 이용해서 캐싱을 하는 전략은 괜찮은 전략입니다만 여유가 있으면 해주세요. (Caffeine등 캐시라이브러리 참조)

4. 재귀호출를 쓰는게 맞는지
깊이에 제한이 없게하려면 재귀호출 밖에 생각이 나지 않아 맵이냐 리스트이냐에 따라서 비교할수 있도록 하였습니다. 이부분도 더 좋은 방법이 있으면 말씀해주시면 감사합니다.

네 재귀호출 사용하시면 됩니다.

추가로 UI쪽에 보이는 부분을 시간이 나시면 다듬어 주시면 좋을듯합니다. 실제로 서비스를 만든다면 어떻게 할까 고민을 해보시고 적용해보세요. jsondiff.com 을 참조해도 좋습니다.
