### ISSUE TITLE
기능 테스트(2)

### ISSUE THREAD

**Issue by jm9293** [jm9293/gettingstarted-kotlin-spring-vue#3]
구현된 기능 정상작동하는 반복테스트

**Comment by kimwz** [comment]
다양한 테스트 케이스들을 만들어서 테스트해보세요 아직 안되는 케이스가 많네요~

**Comment by jm9293** [comment]
넵 다양한 값넣어서 해보겠습니다! . 감사합니다.

2021년 2월 19일 (금) 오후 6:12, Karl Woojung Kim <notifications@github.com>님이 작성:
